name: user-statistician

on:
  schedule:
    - cron: 0 3 * * 1,4
  push:
    branches:
      - main
    paths:
      - .github/workflows/user-statistician.yml
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cicirello/user-statistician@6a7e459d1174b5822afa99a7c6acccf376cb2eb1 # v1.25.0
        with:
          include-title: false
          hide-keys: general, repositories, languages, private, contribTo
          colors: '#2e3440 #2e3440 #81a1c1 #8fbcbb #eceff4'
          image-file: contrib-stats.svg
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
